---
title: "Figure 3 and supplements"
author: NSMR
output: pdf_document
---
```{r}
library(readr)
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(cowplot)

```





Now we'll load up the data, change iteration/phylo_hypothesis to factor type data
```{r}
df_cragi <- readr::read_csv("CRAGI_tidy_corr.csv")
df_calmi <- readr::read_csv("CALMI_tidy_corr.csv")
df_musmu <- readr::read_csv("MUSMU_tidy_corr.csv")
df_mizye <- readr::read_csv("MIZYE_tidy_corr.csv")
df_sacko <- readr::read_csv("SACKO_tidy_corr.csv")
df_strpu <- readr::read_csv("STRPU_tidy_corr.csv")

```


```{r}
map_signif_level <- c(`****` = 1e-04, `***` = 0.001,  `**` = 0.01, `*` = 0.05, ns = 1)

make_plot <- function(tbl,
                      key = "observed",
                      comparisons = list(c("observed", "random")),
                      bracket_y = NULL,
                      ylims = c(-0.5 , 1.5)) {

  if(is.null(bracket_y)) {
    h = ylims[2] - ylims[1]
    bracket_y = c(.9,.825,.75)*h + ylims[1]
  }
  
size.summary <- tbl %>% dplyr::filter(random == "observed") %>%  dplyr::group_by(node, para) %>%  dplyr::summarize(label = paste0("n=",dplyr::n()))
  ggplot(tbl, aes_string(x = 'random', y = 'block_corr', fill = 'random')) +
    #geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
    geom_boxplot(outlier.shape=NA) +
    facet_grid(para ~ node) +
    theme_cowplot(font_size = 6) +
   geom_signif(comparisons = list(c("observed", "random")),
               test = "wilcox.test", test.args = list(paired = FALSE, exact = FALSE), na.rm = TRUE,
               map_signif_level = map_signif_level,
               color="black", tip_length = 0.01, size = .25, textsize = 1,
               y_position = bracket_y,  data = NULL) +
    scale_y_continuous(name = "Block correlation", limits = c(-0.5, 1.5)) +
    theme(legend.title = element_blank(),
          plot.margin = unit(c(1,0,0,0), units='cm'),
          legend.position = 'bottom',
          legend.justification = 'center',
          strip.text = element_text(size = 6, margin = margin(5,0,5,0,'pt')),
          axis.ticks.x = element_blank(),
          axis.title.y = element_text(size = 7),
          axis.text = element_text(size = 6)) +
   geom_text(data = size.summary, aes(x=1, y= 1.2,hjust=0.4,label=label), inherit.aes=F, size = 1)
}

```


Make boxplots
```{r}
p_calmi <- make_plot(df_calmi)
p_cragi <- make_plot(df_cragi)
p_mizye <- make_plot(df_mizye)
p_musmu <- make_plot(df_musmu)
p_sacko <- make_plot(df_sacko)
p_strpu <- make_plot(df_strpu)

ggsave(filename = 'SF7A_calmi_corr_boxplots.pdf',
       plot = p_calmi,
       units = 'cm',
       width = 13,
       height = 7)

ggsave(filename = 'SF7B_cragi_corr_boxplots.pdf',
       plot = p_cragi,
       units = 'cm',
       width = 13,
       height = 7)

ggsave(filename = 'SF7C_mizye_corr_boxplots.pdf',
       plot = p_mizye,
       units = 'cm',
       width = 13,
       height = 7)

ggsave(filename = 'SF7D_musmu_corr_boxplots.pdf',
       plot = p_musmu,
       units = 'cm',
       width = 13,
       height = 7)

ggsave(filename = 'SF7E_sacko_corr_boxplots.pdf',
       plot = p_sacko,
       units = 'cm',
       width = 13,
       height = 7)

ggsave(filename = 'SF7F_strpu_corr_boxplots.pdf',
       plot = p_strpu,
       units = 'cm',
       width = 13,
       height = 7)

```




